### ISSUE TITLE
custom domain for SL

### ISSUE THREAD

**Issue by aguestuser** [advocacycommons/advocacycommons#687]
# Context

> Wanted to work together on getting a proper domain for our Affinity instance. Can you set up Heroku to use groups.swingleft.org as the app's custom domain, and make sure Automated Certificate Management is enabled, to generate SSL certificates for that?

> Doing so will probably prompt you for some sort of domain verification. Pass that info on to me and I'll verify the domain, I think I can just add some DNS TXT records for that, hopefully.

> Then I think all that's left is to double-check the code and make sure it uses relative urls everywhere, or fix any places where it make assumptions about the domain name to use the new subdomain.

> And then if you could also make sure that the code enforces the use of https, redirecting people who come in via http urls.

# Tasks
* [x] enable TLS in heroku
* [x] confirm https enforced
* [x] change `HOSTNAME` config var in `.env.heroku/______` 
* [x] confirm DNS edits w/ client
